





CREATE TABLE CUP_MAEST (
    CUPCOD INTEGER NOT NULL,
    CUPTITULO VARCHAR(200),
    CUPDESCRI VARCHAR(5000),
    CUPIMG VARCHAR(200),
    CUPTIPO INTEGER NOT NULL,
    CUPCLASE INTEGER NOT NULL,
    CUPEST INTEGER)

ALTER TABLE CUP_MAEST
ADD CONSTRAINT PK_CUP_MAEST
PRIMARY KEY (CUPCOD,CUPTIPO,CUPCLASE);



CREATE TABLE CUP_TIPO (
    CUPTIPO INTEGER NOT NULL,
    CUPTIPDES VARCHAR(5000));

ALTER TABLE CUP_TIPO
ADD CONSTRAINT PK_CUP_TIPO
PRIMARY KEY (CUPTIPO);





CREATE TABLE CUP_CLASE (
    CUPCLASE INTEGER NOT NULL,
    CUPCLADES VARCHAR(5000));

ALTER TABLE CUP_CLASE
ADD CONSTRAINT PK_CUP_CLASE
PRIMARY KEY (CUPCLASE);



ALTER TABLE CUP_MAEST ALTER CUPEST TO ESTCODIGO;

COMMENT ON COLUMN CUP_MAEST.ESTCODIGO IS
'';


CREATE SEQUENCE CUP_G;

ALTER SEQUENCE CUP_G RESTART WITH 2;



ALTER TABLE CUP_TIPO
ADD ESTCODIGO INTEGER;


ALTER TABLE CUP_CLASE
ADD ESTCODIGO INTEGER;

