SELECT P.PERCOMPAN,P.PERNOMBRE,P.PERAPELLI,P.PERCORREO,
       E.ENCDESCRI,PR.ENCPREGUN,R.ENCVALRES
FROM ENC_RESP R
LEFT OUTER JOIN PER_MAEST P ON P.PERCODIGO=R.PERCODIGO
LEFT OUTER JOIN ENC_CABE E ON E.ENCREG=R.ENCREG
LEFT OUTER JOIN ENC_PREG PR ON PR.ENCREG=R.ENCREG AND PR.ENCPREITM=R.ENCPREITM
ORDER BY P.PERCOMPAN,P.PERNOMBRE,P.PERAPELLI,E.ENCREG,PR.ENCPREITM;

SELECT DISTINCT P.PERNOMBRE,P.PERAPELLI,P.PERCOMPAN,P.PERCORREO,
        PD.PERNOMBRE,PD.PERAPELLI,PD.PERCOMPAN,PD.PERCORREO
FROM TBL_CHAT C
LEFT OUTER JOIN PER_MAEST P ON P.PERCODIGO=C.PERCODIGO
LEFT OUTER JOIN PER_MAEST PD ON PD.PERCODIGO=C.PERCODDST
WHERE P.PERCODIGO IS NOT NULL AND PD.PERCODIGO IS NOT NULL
ORDER BY P.PERCOMPAN,P.PERNOMBRE,P.PERAPELLI,
        PD.PERCOMPAN,PD.PERNOMBRE,PD.PERAPELLI;
		
SELECT R.REUREG AS REGISTRO,
        R.REUFCHREG AS FECHAREGISTRO,
        R.PERCODSOL,R.PERCODDST,
        CASE R.REUESTADO WHEN 1 THEN 'PENDIENTE' WHEN 2 THEN 'CONFIRMADA' ELSE 'ANULADA' END AS ESTADO,
        R.REUFECHA AS FECHA,R.REUHORA AS HORA,
        R.REUFCHCAN AS FECHACANCELADA,
        PS.PERCOMPAN AS SOLICITANTE_EMPRESA,PS.PERNOMBRE AS SOLICITANTE_NOMBRE, PS.PERAPELLI AS SOLICITANTE_APELLIDO, PS.PERCORREO AS SOLICITANTE_CORREO,
        PD.PERCOMPAN AS DESTINO_EMPRESA,PD.PERNOMBRE AS DESTINO_NOMBRE, PD.PERAPELLI AS DESTINO_APELLIDO, PD.PERCORREO AS DESTINO_CORREO,
        M.MESNUMERO AS MESA
FROM REU_CABE R
LEFT OUTER JOIN PER_MAEST PS ON R.PERCODSOL=PS.PERCODIGO
LEFT OUTER JOIN PER_MAEST PD ON R.PERCODDST=PD.PERCODIGO
LEFT OUTER JOIN MES_MAEST M ON R.MESCODIGO=M.MESCODIGO
WHERE PS.PERCODIGO IS NOT NULL AND PD.PERCODIGO IS NOT NULL
ORDER BY R.REUFCHREG ;		
		